# The name of your Flutter app (used internally)
name: zrc

# A short description that appears in package metadata
description: "A new Flutter project."

# Prevents publishing to pub.dev (recommended for private apps)
publish_to: "none"

# App version: major.minor.patch+build
version: 1.0.6+1

# Dart/Flutter SDK version required for this project
environment:
  sdk: ^3.9.2

# ------------------------------
#        DEPENDENCIES
# ------------------------------
dependencies:
  flutter:
    sdk: flutter # Core Flutter SDK

  # iOS-styled icons
  cupertino_icons: ^1.0.8

  # Package for curved bottom navigation bar
  curved_navigation_bar: ^1.0.6

  # Firebase core (app initialization)
  firebase_core: ^4.2.1

  # State management using BLoC pattern
  flutter_bloc: ^9.1.1

  # Hydration for BLoC
  hydrated_bloc: ^10.1.1

  # Responsive layout for different screen sizes
  flutter_screenutil: ^5.9.3

  # Secure local storage for sensitive data
  flutter_secure_storage: ^9.2.4

  # Display SVG images
  flutter_svg: ^2.2.2

  # Dependency injection (service locator)
  get_it: ^9.0.5

  # Supabase backend SDK (auth, database, storage)
  supabase_flutter: ^2.10.3

  # YouTube player widget for Flutter
  youtube_player_flutter: ^9.1.3

  # Internationalization
  intl: ^0.20.2

  # Localization
  easy_localization: ^3.0.8

  # Arabic to Roman converter
  arabic_roman_conv: ^0.1.0-dev.2

  # Translation
  translator: ^1.0.4+1
  path_provider: ^2.1.5

  image_picker: ^1.2.1

  flutter_native_splash: ^2.4.7
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.4
  path_provider_platform_interface: ^2.1.2
  shorebird_code_push: ^2.0.5

# ------------------------------
#        DEV DEPENDENCIES
# ------------------------------
dev_dependencies:
  # Recommended lint rules
  flutter_lints: ^6.0.0

  # Flutter test framework
  flutter_test:
    sdk: flutter

# ------------------------------
#        FLUTTER SETTINGS
# ------------------------------
flutter:
  # Enables Material Design icons and theming
  uses-material-design: true

  # Asset folders included in the build
  assets:
    - assets/images/
    - assets/svgs/
    - assets/translations/
    - shorebird.yaml # Localization assets

  #        CUSTOM FONTS
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200

    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200


# ------------------------------
#        LAUNCHER ICONS
# ------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true

  # For non-Android platforms (icon with background baked in)
  image_path: assets/images/splash_dark.png